/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package likedsongs;

/**
 *
 * @author conor
 */
public class LikedSongsGUI extends javax.swing.JFrame {

    /**
     * Creates new form LikedSongsGUI
     */
    private LikedSongsIF2 songs;
    private LikedSongsIF genreA, genreB;

    public LikedSongsGUI() {
        initComponents();
        LikedSongs ls = new LikedSongs();
        Genre a = new Genre();
        genreB b = new genreB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryLBL = new javax.swing.JLabel();
        entryTF = new javax.swing.JTextField();
        genreLBL = new javax.swing.JLabel();
        genreTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lkdSgTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        rapGnrTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        popGnrTA = new javax.swing.JTextArea();
        addBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        dltBTN = new javax.swing.JButton();
        moveBTN = new javax.swing.JButton();
        dspBTN = new javax.swing.JButton();
        sffBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entryLBL.setText("Enter Song:");

        entryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTFActionPerformed(evt);
            }
        });

        genreLBL.setText("Song Genre:");

        lkdSgTA.setColumns(20);
        lkdSgTA.setRows(5);
        jScrollPane1.setViewportView(lkdSgTA);

        rapGnrTA.setColumns(20);
        rapGnrTA.setRows(5);
        jScrollPane2.setViewportView(rapGnrTA);

        popGnrTA.setColumns(20);
        popGnrTA.setRows(5);
        jScrollPane3.setViewportView(popGnrTA);

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("Search");

        dltBTN.setText("Delete");
        dltBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltBTNActionPerformed(evt);
            }
        });

        moveBTN.setText("Move");

        dspBTN.setText("Display");

        sffBTN.setText("Shuffle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(entryLBL)
                            .addGap(18, 18, 18)
                            .addComponent(entryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(addBTN)
                    .addComponent(moveBTN))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(genreLBL)
                            .addGap(18, 18, 18)
                            .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(searchBTN)
                    .addComponent(dspBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dltBTN)
                    .addComponent(sffBTN))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryLBL)
                    .addComponent(entryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreLBL)
                    .addComponent(genreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(searchBTN)
                    .addComponent(dltBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveBTN)
                    .addComponent(dspBTN)
                    .addComponent(sffBTN))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTFActionPerformed

    private void dltBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltBTNActionPerformed
        // TODO add your handling code here:
        // Assuming songs is an ArrayList<String> or ArrayList<Object>
// Initialize songs appropriately in your LikedSongsGUI class

        /*if (this.songs == null || this.songs.isEmpty()) {
            lkdSgTA.append("There are no wagons to be removed!\n");
        } else {
            String songsRemoved = this.songs.remove(this.songs.size() - 1);
            lkdSgTA.append("The " + songsRemoved + " wagon was removed!\n");
        }*/


    }//GEN-LAST:event_dltBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String name, genre;
        LikedSongs ls = new LikedSongs();

        name = entryTF.getText();
        ls.push(name);
        lkdSgTA.append("The song " + name + " was added!\n");
    }//GEN-LAST:event_addBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LikedSongsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LikedSongsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LikedSongsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LikedSongsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LikedSongsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton dltBTN;
    private javax.swing.JButton dspBTN;
    private javax.swing.JLabel entryLBL;
    private javax.swing.JTextField entryTF;
    private javax.swing.JLabel genreLBL;
    private javax.swing.JTextField genreTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea lkdSgTA;
    private javax.swing.JButton moveBTN;
    private javax.swing.JTextArea popGnrTA;
    private javax.swing.JTextArea rapGnrTA;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton sffBTN;
    // End of variables declaration//GEN-END:variables
}
